### ISSUE TITLE
Automatic deployment to GP Pages

### ISSUE THREAD

**Issue by sebald** [marigold-ui/search-form-pattern#1]
- Deploy `main` branch (every time a new commit happens)
- Use GH Pages for hosting (either: https://create-react-app.dev/docs/deployment/#github-pages or https://github.com/marketplace/actions/deploy-to-github-pages)

**Comment by benediktgrether** [comment]
The repository now has a Github action that runs a build command every time a branch is merged into master, and then makes it available on Github pages.
