### ISSUE TITLE
Persist state on reload/refresh + make URLs sharable

### ISSUE THREAD

**Issue by sebald** [marigold-ui/search-form-pattern#3]
**Problem:** When refreshing the site my search and its results are gone 😢 Also, I can not share theresultst with colleagues!

---

- Persist state even when site is reloaded
- Update URL (search params) based on search input

---

Examples:

- https://streamich.github.io/react-use/?path=/story/sensors-usesearchparam--docs
- https://reactrouter.com/en/6.4.1/hooks/use-search-params (needs `react-router` though)

**Comment by sarahgm** [comment]
closed with #6
